INSERT INTO "sensors" ("id", "type", "subtype", "location", "unit") VALUES
('TSH000ED',	'Temperature',	NULL,	'East End',	'C'),
('TSH000WD',	'Temperature',	NULL,	'West End',	'C'),
('TSH000CDT',	'Temperature',	NULL,	'Ceil',	'C'),
('TSH000CDB',	'Temperature',	NULL,	'Bottom',	'C'),
('GPH000EDE',	'GPS',	'Longitude',	'East Side',	'degrees'),
('GPH000EDN',	'GPS',	'Latitude',	'East Side',	'degrees'),
('GPH000EDH',	'GPS',	'Height',	'East Side',	'metre'),
('GPH000WDE',	'GPS',	'Longitude',	'West Side',	'degrees'),
('GPH000WDN',	'GPS',	'Latitude',	'West Side',	'degrees'),
('GPH000WDH',	'GPS',	'Height',	'West Side',	'metre'),
('GPH000dDE',	'GPS',	NULL,	NULL,	'metre'),
('GPH000dDN',	'GPS',	NULL,	NULL,	'metre'),
('GPH000dDH',	'GPS',	NULL,	NULL,	'metre'),
('EXH077ED',	'Extensometer',	NULL,	'East Side Hessle Tower',	'mm'),
('HBB_WIH000CDS',	'Meteo,HBB',	'Wind Speed',	'Midspan',	'm/sec'),
('HBB_WIH000CDD',	'Meteo,HBB',	'Wind Direction',	'Midspan',	'degrees'),
('HBB_TSH000CDS',	'Meteo,HBB',	'Surface Temperature',	'Midspan',	'C'),
('HBB_TSH000CDG',	'Meteo,HBB',	'Ground Temperature',	'Midspan',	'C'),
('HBB_TSH000CDA',	'Meteo,HBB',	'Air Temperature',	'Midspan',	'C'),
('NOAA_WIS',	'Meteo,NOAA',	'Wind Speed',	'Humberside Airport',	'm/sec'),
('NOAA_WID',	'Meteo,NOAA',	'Wind Direction',	'Humberside Airport',	'degrees'),
('NOAA_TS',	'Meteo,NOAA',	'Temperature',	'Humberside Airport',	'C'),
('WIH000CDS',	'Meteo',	'Wind Speed',	'Midspan',	'degrees'),
('WIH000CDD',	'Meteo',	'Wind Direction',	'Midspan',	'C'),
('EXH077WD',	'Extensometer',	NULL,	'West Side Hessle Tower',	'mm'),
('EXB077ED',	'Extensometer',	NULL,	'East Side Barton Tower',	'mm'),
('EXB077WD',	'Extensometer',	NULL,	'West Side Barton Tower',	'mm'),
('EXH077dD',	'Extensometer',	NULL,	NULL,	'mm'),
('EXB077dD',	'Extensometer',	NULL,	NULL,	'mm'),
('GPH000EDE_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000EDN_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000EDH_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000WDE_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000WDN_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000WDH_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000dDE_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000dDN_RMS',	'GPS',	NULL,	NULL,	'm'),
('GPH000dDH_RMS',	'GPS',	NULL,	NULL,	'm'),
('EXH077ED_RMS',	'Extensometer',	NULL,	NULL,	'm'),
('EXH077WD_RMS',	'Extensometer',	NULL,	NULL,	'm'),
('EXB077ED_RMS',	'Extensometer',	NULL,	NULL,	'm'),
('EXB077WD_RMS',	'Extensometer',	NULL,	NULL,	'm'),
('EXH077dD_RMS',	'Extensometer',	NULL,	NULL,	'm'),
('EXB077dD_RMS',	'Extensometer',	NULL,	NULL,	'm'),
('TSH077ED',	'Extensometer',	'Temperature',	'East Side Hessle Tower',	'C'),
('TSH077WD',	'Extensometer',	'Temperature',	'West Side Hessle Tower',	'C'),
('TSB077ED',	'Extensometer',	'Temperature',	'East Side Barton Tower',	'C'),
('TSB077WD',	'Extensometer',	'Temperature',	'West Side Barton Tower',	'C'),
('INH000CDN',	'Inclinometer',	'',	'Northbound',	'm/m'),
('INH000CDW',	'Inclinometer',	NULL,	'Westbound',	'm/m'),
('INH000CDN_RMS',	'Inclinometer',	NULL,	NULL,	'm/m'),
('INH000CDW_RMS',	'Inclinometer',	NULL,	NULL,	'm/m'),
('TSH000CDI',	'Inclinometer',	'Temperature',	'Nivel220',	'C'),
('RMS_VE',	'Accelerometer',	'Vertical',	'East Side',	'g'),
('RMS_VW',	'Accelerometer',	'Vertical',	'West Side',	'g'),
('RMS_H',	'Accelerometer',	'Lateral',	'East Side',	'g'),
('RMS_VM',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VS1',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VA1',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VS2a',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VS2b',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VA2',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VS3',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_TS1',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VA3',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VS4',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_TA1',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VA4',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VS5',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_TS2',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_VA5',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LS1',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LA1',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LS2a',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LS2b',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LS2c',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LA2a',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LA2b',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LA2c',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LS2d',	'Accelerometer',	NULL,	NULL,	'g'),
('RMS_LS3',	'Accelerometer',	NULL,	NULL,	'g'),
('FREQ_VS1',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VA1',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VS2a',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VS2b',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VA2',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VS3',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_TS1',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VA3',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VS4',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_TA1',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VA4',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VS5',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_TS2',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_VA5',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LS1',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LA1',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LS2a',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LS2b',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LS2c',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LA2a',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LA2b',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LA2c',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LS2d',	'Accelerometer',	NULL,	NULL,	'Hz'),
('FREQ_LS3',	'Accelerometer',	NULL,	NULL,	'Hz'),
('DAMP_VS1',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VA1',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VS2a',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VS2b',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VA2',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VS3',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_TS1',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VA3',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VS4',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_TA1',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VA4',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VS5',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_TS2',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_VA5',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LS1',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LA1',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LS2a',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LS2b',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LS2c',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LA2a',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LA2b',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LA2c',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LS2d',	'Accelerometer',	NULL,	NULL,	'%'),
('DAMP_LS3',	'Accelerometer',	NULL,	NULL,	'%'),
('WIM_GROSS',	'Gross',	NULL,	NULL,	'kg'),
('SCADA_AIR_TEMPERATURE',	'Scada',	'Air Temperature',	NULL,	'C'),
('SCADA_WIND_SPEED',	'Scada',	'Wind Speed',	NULL,	'm/s'),
('SCADA_WIND_DIRECTION',	'Scada',	'Wind Direction',	NULL,	'degrees');
